#!/usr/bin/perl
use strict;
use warnings;
use pf::config;
use feature "say";
use Log::Log4perl;
use Readonly;
use JSON;
use HTTP::Headers;
use HTTP::Request;
use LWP::UserAgent;

# Configuration parameter
Readonly::Scalar my $WEBAPI_SCHEME   => 'http';
Readonly::Scalar my $WEBAPI_PORT     => $Config{'ports'}{'soap'};
Readonly::Scalar my $WEBAPI_RESOURCE => 'json';
Readonly::Scalar my $WEBAPI_URI      => 
    $WEBAPI_SCHEME . '://' . 'localhost' . ':' . $WEBAPI_PORT . '/' . $WEBAPI_RESOURCE;

print STDERR "Loaded the perl snmptrapd handler\n";

NetSNMP::TrapReceiver::register( "all", \&trap_receiver )
    || warn "failed to register our perl trap handler\n";

sub trap_receiver {
    my %PDU      = %{ $_[0] };
    my @VARBINDS = @{ $_[1] };

    my %VARBINDS
        = map { $_->[0] => ( sprintf "type=%-2d value=%s", $_->[2], $_->[1] ); } @VARBINDS;

    my %trap = (
        PDU      => \%PDU,
        VARBINDS => \%VARBINDS,
        PFTYPE   => undef,
    );
    $trap{"PFTYPE"} = "snmptrap";
    my $json = encode_json \%trap;

    #print $json . "\n\n";
    my $req = HTTP::Request->new( 'POST', $WEBAPI_URI );
    $req->header( 'Content-Type' => 'application/json' );
    $req->header( 'Request'      => 'snmptrap' );
    $req->content($json);

    my $lwp = LWP::UserAgent->new;
    $logger->info("Calling WebAPI with $request request for mac $mac on switch $switch");
    $lwp->request($req);

    return 1;

}

